substitutions:
  name: alarm-clock-2-8-round-prototype
  friendly_name: Alarm Clock Round Touch Prototype
  animation_speed: 500ms
  number_of_timers: "5"

packages:
  common: !include 2.8_round_alarm_clock_packages/common.yaml
  debugging: !include 2.8_round_alarm_clock_packages/debugging.yaml
  theming: !include 2.8_round_alarm_clock_packages/theming.yaml
  clockface_abstraction: !include 2.8_round_alarm_clock_packages/clockface_abstraction.yaml
  clockface_seven_segment: !include 2.8_round_alarm_clock_packages/clockface_seven_segment.yaml
  clockface_analog: !include 2.8_round_alarm_clock_packages/clockface_analog.yaml
  page_clockface: !include 2.8_round_alarm_clock_packages/page_clockface.yaml # Make sure the clockface page is included first so that it will be the first page displayed
  page_configuration: !include 2.8_round_alarm_clock_packages/page_configuration.yaml
  page_menu: !include 2.8_round_alarm_clock_packages/page_menu.yaml
  alarm_one: !include
    file: 2.8_round_alarm_clock_packages/alarm.yaml
    vars:
      name: alarm_one
      friendly_name: Alarm One
  alarm_two: !include
    file: 2.8_round_alarm_clock_packages/alarm.yaml
    vars:
      name: alarm_two
      friendly_name: Alarm Two

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options: 
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_FLASHMODE_QIO: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_IDF_EXPERIMENTAL_FEATURES: y
      CONFIG_COMPILER_OPTIMIZATION_PERF: y
      CONFIG_LV_MEMCPY_MEMSET_STD: y
      CONFIG_LV_ATTRIBUTE_FAST_MEM_USE_IRAM: y
      CONFIG_I2S_SUPPRESS_DEPRECATE_WARN: y
      # CONFIG_ESPTOOLPY_FLASHFREQ_120M: y
      # CONFIG_BOOTLOADER_FLASH_DC_AWARE: y

# Write preferences to flash a little more frequently
preferences:
  flash_write_interval: 15s

external_components:
  - source: github://pr#8494
    components: [lvgl]
  - source:
      type: local
      path: components
    components: [qmi8658]

logger:
  # level: WARN
  # level: VERY_VERBOSE

psram:
  # Supposedly octal mode does not work at 120MHz
  # My testing shows otherwise, but it's not a huge difference in performance
  # More testing needed, especially to validate stability
  # https://github.com/esphome/esphome/pull/8477
  mode: octal
  speed: 80MHz

ota:
  - platform: esphome
    password: !secret ota_password
    on_begin:
      then:
        - logger.log: "Changing screen to updating"
        - lvgl.page.show: updating
        - logger.log: "Running LVGL loop"
        - lambda: "id(lvgl_main).loop();"
        - logger.log: "Update screen prep complete"
    on_progress:
      then:
        - lvgl.bar.update:
            id: update_progress_bar
            value: !lambda "return (int)x;"
        - lambda: "id(lvgl_main).loop();"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  output_power: "10dB"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: ""

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

captive_portal:
    
web_server:
  id: my_web_server
  port: 80
  version: 3
  sorting_groups:
    - id: clockface_settings
      name: Clockface Settings

i2c:
  - id: i2c_bus
    sda: GPIO15
    scl: GPIO07
    frequency: 100kHz

i2s_audio:
  i2s_lrclk_pin: GPIO19  # D- on 12-pin connector
  i2s_bclk_pin: GPIO20   # D+ on 12-pin connector

speaker:
  - platform: i2s_audio
    id: i2s_audio_speaker
    dac_type: external
    buffer_duration: 100ms
    bits_per_sample: 32bit
    sample_rate: 48000
    i2s_dout_pin: GPIO43 # TXD on 12-pin connector

  # Virtual speakers to combine the announcement and media streams together into one output
  - platform: mixer
    id: mixing_speaker
    output_speaker: i2s_audio_speaker
    num_channels: 2
    source_speakers:
      - id: announcement_mixing_input
        timeout: never
        bits_per_sample: 16
      - id: media_mixing_input
        timeout: never
        bits_per_sample: 16

  # Vritual speakers to resample each pipelines' audio, if necessary, as the mixer speaker requires the same sample rate
  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 48000
    bits_per_sample: 16
  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

media_player:
  - platform: speaker
    id: alarm_clock_media_player
    name: Media Player
    internal: False
    volume_increment: 0.05
    volume_min: 0.4
    volume_max: 1.0
    buffer_size: 1000000
    announcement_pipeline:
      speaker: announcement_resampling_speaker
      format: FLAC     # FLAC is the least processor intensive codec
      num_channels: 1  # Stereo audio is unnecessary for announcements
      sample_rate: 48000
    media_pipeline:
      speaker: media_resampling_speaker
      format: FLAC     # FLAC is the least processor intensive codec
      num_channels: 1
      sample_rate: 48000
    on_announcement:
      - mixer_speaker.apply_ducking:
          id: media_mixing_input
          decibel_reduction: 20
          duration: 0.0s

# SPI for ST7701S Display
spi:
  - id: spi_lcd
    clk_pin: GPIO02
    mosi_pin: GPIO01
    interface: hardware

# TCA9554 GPIO extender
pca9554:
  - id: gpio_expander
    i2c_id: i2c_bus 
    address: 0x20

switch:
  - platform: gpio
    pin:
      pca9554: gpio_expander
      number: 7
    name: "Buzzer"


# Backlight PWM output and light component
output:
    # Backlight LED
  - platform: ledc
    id: gpio_backlight_pwm
    pin: GPIO06
    # frequency: 2000Hz
    channel: 0

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    id: display_backlight
    restore_mode: RESTORE_AND_ON
    gamma_correct: 1
    web_server:
      sorting_group_id: clockface_settings

touchscreen:
  - platform: gt911
    id: my_touchscreen
    i2c_id: i2c_bus
    address: 0x5D
    reset_pin:
      pca9554: gpio_expander
      number: 1
    interrupt_pin: GPIO16

display:
  - platform: st7701s
    id: my_display
    spi_id: spi_lcd
    spi_mode: MODE1
    color_order: bgr
    auto_clear_enabled: false
    data_rate: 10MHz
    dimensions:
      width: 480
      height: 480
    cs_pin:
      pca9554: gpio_expander
      number: 2
    reset_pin:
      pca9554: gpio_expander
      number: 0
    de_pin: GPIO40
    hsync_pin: GPIO38
    vsync_pin: GPIO39
    pclk_pin: GPIO41
    hsync_back_porch: 2
    hsync_front_porch: 2
    hsync_pulse_width: 2
    vsync_back_porch: 2
    vsync_front_porch: 2
    vsync_pulse_width: 2
    init_sequence:
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x13 ]
      - [ 0xEF, 0x08 ]
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x10 ]
      - [ 0xC0, 0x3B, 0x00 ]
      - [ 0xC1, 0x10, 0x0C ]
      - [ 0xC2, 0x07, 0x0A ]
      - [ 0xC7, 0x00 ]
      - [ 0xCC, 0x10 ]
      - [ 0xCD, 0x08 ]
      - [ 0xB0, 0x05, 0x12, 0x98, 0x0E, 0x0F, 0x07, 0x07, 0x09, 0x09, 0x23, 0x05, 0x52, 0x0F, 0x67, 0x2C, 0x11 ]
      - [ 0xB1, 0x0B, 0x11, 0x97, 0x0C, 0x12, 0x06, 0x06, 0x08, 0x08, 0x22, 0x03, 0x51, 0x11, 0x66, 0x2B, 0x0F ]
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x11 ]
      - [ 0xB0, 0x5D ]
      - [ 0xB1, 0x3E ]
      - [ 0xB2, 0x81 ]
      - [ 0xB3, 0x80 ]
      - [ 0xB5, 0x4E ]
      - [ 0xB7, 0x85 ]
      - [ 0xB8, 0x20 ]
      - [ 0xC1, 0x78 ]
      - [ 0xC2, 0x78 ]
      - [ 0xD0, 0x88 ]
      - [ 0xE0, 0x00, 0x00, 0x02 ]
      - [ 0xE1, 0x06, 0x30, 0x08, 0x30, 0x05, 0x30, 0x07, 0x30, 0x00, 0x33, 0x33 ]
      - [ 0xE2, 0x11, 0x11, 0x33, 0x33, 0xF4, 0x00, 0x00, 0x00, 0xF4, 0x00, 0x00, 0x00 ]
      - [ 0xE3, 0x00, 0x00, 0x11, 0x11 ]
      - [ 0xE4, 0x44, 0x44 ]
      - [ 0xE5, 0x0D, 0xF5, 0x30, 0xF0, 0x0F, 0xF7, 0x30, 0xF0, 0x09, 0xF1, 0x30, 0xF0, 0x0B, 0xF3, 0x30, 0xF0 ]
      - [ 0xE6, 0x00, 0x00, 0x11, 0x11 ]
      - [ 0xE7, 0x44, 0x44 ]
      - [ 0xE8, 0x0C, 0xF4, 0x30, 0xF0, 0x0E, 0xF6, 0x30, 0xF0, 0x08, 0xF0, 0x30, 0xF0, 0x0A, 0xF2, 0x30, 0xF0 ]
      - [ 0xE9, 0x36, 0x01 ]
      - [ 0xEB, 0x00, 0x01, 0xE4, 0xE4, 0x44, 0x88, 0x40 ]
      - [ 0xED, 0xFF, 0x10, 0xAF, 0x76, 0x54, 0x2B, 0xCF, 0xFF, 0xFF, 0xFC, 0xB2, 0x45, 0x67, 0xFA, 0x01, 0xFF ]
      - [ 0xEF, 0x08, 0x08, 0x08, 0x45, 0x3F, 0x54 ]
      - [ 0xFF, 0x77, 0x01, 0x00, 0x00, 0x00 ]
      - delay 120ms
      - [ 0x11 ]
      - delay 120ms
      - [ 0x3A, 0x66 ]
      - [ 0x36, 0x00 ]
      - [ 0x35, 0x00 ]
      - [ 0x20 ]
      - delay 120ms
      - [ 0x29 ]
    data_pins:
      red:
        - GPIO46       #r1
        - GPIO3        #r2
        - GPIO8        #r3
        - GPIO18       #r4
        - GPIO17       #r5
      green:
        - GPIO14       #g0
        - GPIO13       #g1
        - GPIO12       #g2
        - GPIO11       #g3
        - GPIO10       #g4
        - GPIO9        #g5
      blue:
        - GPIO5        #b1
        - GPIO45       #b2
        - GPIO48       #b3
        - GPIO47       #b4
        - GPIO21       #b5

time:
  - platform: pcf85063
    id: pcf85063_time
    i2c_id: i2c_bus
    address: 0x51
  - platform: sntp
    id: sntp_time
    timezone: America/Chicago
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    on_time_sync: 
      then:
        - logger.log: "SNTP: time has synchronized"

sensor:
  - platform: qmi8658
    i2c_id: i2c_bus
    address: 0x6B
    update_interval: 5s
    accel_x:
      name: "QMI8658 Accelerometer X"
      id: accel_x
      unit_of_measurement: "g"
      accuracy_decimals: 2
    accel_y:
      name: "QMI8658 Accelerometer Y"
      id: accel_y
      unit_of_measurement: "g"
      accuracy_decimals: 2
    accel_z:
      name: "QMI8658 Accelerometer Z"
      id: accel_z
      unit_of_measurement: "g"
      accuracy_decimals: 2
    gyro_x:
      name: "QMI8658 Gyroscope X"
      id: gyro_x
      unit_of_measurement: "dps"
      accuracy_decimals: 2
    gyro_y:
      name: "QMI8658 Gyroscope Y"
      id: gyro_y
      unit_of_measurement: "dps"
      accuracy_decimals: 2
    gyro_z:
      name: "QMI8658 Gyroscope Z"
      id: gyro_z
      unit_of_measurement: "dps"
      accuracy_decimals: 2
