substitutions:
  name: alarm-clock-prototype-host
  friendly_name: Alarm Clock Prototype Host
  page_change_animation: FADE_IN
  animation_speed: 500ms
  timezone: America/Chicago
  font_default: montserrat_24
  font_large: montserrat_30
  font_xlarge: montserrat_36
  font_xxlarge: montserrat_40

packages:
  common: !include 2.8_round_alarm_clock_packages/common.yaml
  debugging: !include 2.8_round_alarm_clock_packages/debugging.yaml
  theming: !include 2.8_round_alarm_clock_packages/theming.yaml
  clockface_abstraction: !include 2.8_round_alarm_clock_packages/clockface_abstraction.yaml
  clockface_seven_segment: !include 2.8_round_alarm_clock_packages/clockface_seven_segment.yaml
  clockface_analog: !include 2.8_round_alarm_clock_packages/clockface_analog.yaml
  page_clockface: !include 2.8_round_alarm_clock_packages/page_clockface.yaml # Make sure the clockface page is included first so that it will be the first page displayed
  page_configuration: !include 2.8_round_alarm_clock_packages/page_configuration.yaml
  page_menu: !include 2.8_round_alarm_clock_packages/page_menu.yaml
  alarm_one: !include
    file: 2.8_round_alarm_clock_packages/alarm.yaml
    vars:
      name: alarm_one
      friendly_name: Alarm One
      next_alarm: alarm_configuration_alarm_two
      prev_alarm: alarm_configuration_alarm_three
  alarm_two: !include
    file: 2.8_round_alarm_clock_packages/alarm.yaml
    vars:
      name: alarm_two
      friendly_name: Alarm Two
      next_alarm: alarm_configuration_alarm_three
      prev_alarm: alarm_configuration_alarm_one
  alarm_three: !include
    file: 2.8_round_alarm_clock_packages/alarm.yaml
    vars:
      name: alarm_three
      friendly_name: Alarm Three
      next_alarm: alarm_configuration_alarm_one
      prev_alarm: alarm_configuration_alarm_two

host:

logger:
  # level: WARN
  # level: VERY_VERBOSE

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    - priority: -200 # LVGL runs with setup_priority::PROCESSOR which is 400.  We want to run this just after LVGL is initialized
      then:
        - logger.log: "Beginning initialization"
        - script.execute: initialize_clock
        - wait_until:
          - not:
            - script.is_running: initialize_clock
        - lvgl.page.show: alarm_configuration_alarm_one

# Write preferences to flash a little more frequently
preferences:
  flash_write_interval: 15s

external_components:
  - source: github://pr#8494
    components: [lvgl]

switch:
  # This is a do-nothing switch.  It's only here to mock the buzzer on the actual device and allow the buzzer id to resolve to something
  # when referenced in other places in the firmware.
  - id: buzzer
    platform: template
    name: "Buzzer"
    optimistic: true
    turn_on_action:
      - logger.log: "Buzzer go BUZZZZ!"
    turn_off_action:
      - logger.log: "Buzzer NOT go BUZZZ!"


touchscreen:
  platform: sdl

display:
  - platform: sdl
    dimensions:
      width: 480
      height: 480

time:
  - platform: host
    id: sntp_time
    timezone: ${timezone}
    on_time_sync:
      then:
        - logger.log: "SNTP: time has synchronized"

lvgl:
  id: lvgl_main
  top_layer:
    widgets:
      - obj:
          id: device_screen_area
          align: CENTER
          width: 100%
          height: 100%
          border_color: 0xFF0000
          border_side: [TOP,BOTTOM,LEFT,RIGHT]
          border_width: 1
          border_opa: 50%
          radius: 240
