esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  # min_version: 2025.4  # TODO: Uncomment this and set it to whatever version PR#8494 makes it into which should be 2025.4
  on_boot:
    - priority: -200 # LVGL runs with setup_priority::PROCESSOR which is 400.  We want to run this just after LVGL is initialized
      then:
        - script.execute: initialize_clock

# Enable logging
logger:

button:
  - platform: restart
    name: "Restart"

interval:
  - interval: 1s
    then:
      - if:
          condition:
            time.has_time:
          then:
            # - logger.log:
            #     format: "Time tick: hour: %d, minute: %d, second: %d"
            #     args: ['id(sntp_time).now().hour', 'id(sntp_time).now().minute', 'id(sntp_time).now().second']
            - script.execute: time_tick

script:
  # This script gets called every second by the time component but will only take action if the system has completed initialization
  - id: time_tick
    then:
      - if:
          condition:
            lambda: "return id(system_initialized);"
          then:
            - script.execute:
                id: render_time_display
                full: false
      - if:
          condition:
            lambda: "return id(sntp_time).now().second == 0;"
          then:
            - logger.log: "Running alarm check scripts"
            - script.execute: alarm_one_script_check
            - script.execute: alarm_two_script_check

lvgl:
  id: lvgl_main
  default_font: font_default
  disp_bg_color: background_color
  disp_bg_opa: COVER
  buffer_size: 1.0
  # buffer_size: 0.12
  # buffer_size: 0.25
  top_layer:
    widgets:
      - obj:
          id: boot_screen
          x: 0
          y: 0
          width: 100%
          height: 100%
          bg_color: background_color
          bg_opa: COVER
          radius: 0
          pad_all: 0
          border_width: 0
          widgets:
            - image:
                align: CENTER
                src: boot_logo
                y: -40
            - spinner:
                align: CENTER
                y: 95
                height: 50
                width: 50
                spin_time: 1s
                arc_length: 60deg
                arc_width: 8
                indicator:
                  arc_color: 0x18bcf2
                  arc_width: 8
  pages:
    - id: updating
      styles: page_background
      skip: true
      widgets:
        - bar:
            id: update_progress_bar
            align: CENTER
