esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot: 
    - priority: -100  # LVGL runs with setup_priority::PROCESSOR which is 400.  We want to run this just after LVGL is initialized
      then:
      - script.execute: initialize_clock

# Enable logging
logger: