script:
  - id: initialize_clock
    then:
      - lvgl.page.show: home
      - logger.log: "Configuring seconds display"
      - script.execute: script_toggle_show_seconds
      - logger.log: "Waiting for time sync"
      - wait_until:
          time.has_time:
      - logger.log: "Updating time display"
      - script.execute: update_time_display
      - logger.log: "Bootup complete, showing home screen"
      - wait_until:
          lvgl.page.is_showing: home # We told it go to to the home page, but this can take some time.  Sometimes it takes more time than all the other initialization.
      - lvgl.widget.hide: boot_screen

  - id: script_toggle_show_seconds
    then:
      - if:
          condition:
            - switch.is_on: switch_show_seconds
          then:
            - lvgl.label.update:
                id: time_background
                text: 88:88:88
          else:
            - lvgl.label.update:
                id: time_background
                text: 88:88
      - script.execute: update_time_display

switch:
  - platform: lvgl
    id: switch_show_seconds
    widget: checkbox_time_display_seconds
    name: Show Seconds
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - script.execute: script_toggle_show_seconds
    on_turn_off:
      - script.execute: script_toggle_show_seconds

image:
  - file: https://esphome.io/_static/favicon-512x512.png
    id: boot_logo
    resize: 200x200
    type: RGB565
    transparency: alpha_channel

lvgl:
  id: lvgl_main
  disp_bg_color: 0x000000
  disp_bg_opa: COVER
  default_font: montserrat_24
  top_layer:
    widgets:
      - buttonmatrix:
          id: navigation
          styles: header_footer
          align: TOP_MID
          pad_all: 0
          outline_width: 0
          items:
            styles: header_footer
          rows:
            - buttons:
              - id: button_goto_configuration
                text: "CONF"
                on_press:
                  then:
                    - lvgl.page.show:
                        id: configuration
                        animation: ${page_change_animation}
                        time: ${animation_speed}
              - id: button_goto_home
                text: "HOME"
                on_press:
                  then:
                    - lvgl.page.show:
                        id: home
                        animation: ${page_change_animation}
                        time: ${animation_speed}
              - id: button_goto_status
                text: "STATUS"
                on_press:
                  then:
                    - lvgl.page.show:
                        id: status
                        animation: ${page_change_animation}
                        time: ${animation_speed}

      - obj:
          id: boot_screen
          x: 0
          y: 0
          width: 100%
          height: 100%
          bg_color: background_color
          bg_opa: COVER
          radius: 0
          pad_all: 0
          border_width: 0
          widgets:
            - image:
                align: CENTER
                src: boot_logo
                y: -40
            - spinner:
                align: CENTER
                y: 95
                height: 50
                width: 50
                spin_time: 1s
                arc_length: 60deg
                arc_width: 8
                indicator:
                  arc_color: 0x18bcf2
                  arc_width: 8
  pages: 
    - id: configuration
      styles: page_background
      widgets:
        - obj:
            align: CENTER
            width: 100%
            height: 100%
            layout:
              type: grid
              grid_rows: [FR(1),FR(1),FR(1),FR(1),FR(1),FR(1)]
              grid_columns: [FR(1),FR(1)]
            widgets:
              - label:
                  text: "Timezone"
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 0
              - dropdown:
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 1
                  width: 300
                  options:
                    - America/Chicago
                    - two49
                    - three
              - label:
                  text: "Show Seconds"
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 0
              - checkbox:
                  id: checkbox_time_display_seconds
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 1
                  text: ""
    - id: updating
      styles: page_background
      skip: true
      widgets:
        - bar:
            id: update_progress_bar
            align: CENTER
